language: java

sudo: false

jdk:
  - oraclejdk8

script: mvn clean package

env:
  global:
    - JAVA_OPTS="-XX:+TieredCompilation -XX:TieredStopAtLevel=1 -Xmn48M -Xmx512M"
    - NUM_THREADS=2

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/969b5598af30afd3e0a2
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
